import { useState } from 'react';
import DateField from '../components/DateField';
import SiteFooter from '../components/SiteFooter';
import PhoneInput from '../components/PhoneInput';

export default function CareersPage({ onNavigate }) {
  const [applicationSent, setApplicationSent] = useState(false);
  return <main className="content-page careers-page"><header className="content-page-heading"><span>CAREERS · ACCRA</span><h1>Join our<br />creative team.</h1></header><section className="career-layout"><div className="career-role"><span>OPEN POSITION</span><h2>Content Creator &amp;<br />Social Media Manager</h2><p>We are looking for a creative, passionate and trend-aware person to manage content and grow our online community.</p><a className="primary-action" href="#application">START APPLICATION</a></div><div className="career-details"><article><h3>Key responsibilities</h3><ul><li>Create engaging content for social platforms</li><li>Plan and manage the content calendar</li><li>Shoot and edit polished photos, videos and graphics</li><li>Monitor trends and suggest creative ideas</li><li>Engage followers and help grow the community</li><li>Review performance and provide monthly reports</li></ul></article><article><h3>What we are looking for</h3><ul><li>Experience in content creation or social media</li><li>Clear written and verbal communication</li><li>Confidence using content creation tools</li><li>Strong understanding of social trends and analytics</li><li>Independent, detail-oriented working style</li><li>Interest in branding, storytelling and engagement</li></ul></article><article><h3>What we offer</h3><ul><li>Competitive salary</li><li>Creative and supportive work environment</li><li>Opportunities for growth and development</li><li>A chance to shape a growing Ghanaian gifting brand</li></ul></article></div></section><section className="application-section" id="application"><div><span>APPLICATION</span><h2>Tell us about<br />your work.</h2><p>Share the details that help the team understand your experience and creative point of view.</p></div><form onSubmit={event => { event.preventDefault(); setApplicationSent(true); }}><div className="application-grid"><label>Full name<input required /></label><label>Email address<input required type="email" /></label><PhoneInput label="Phone / WhatsApp" required /><label>Current location<input required /></label><label>Portfolio or social link<input required type="url" placeholder="https://" /></label><DateField label="Earliest start date" prefix="career" /></div><label>Relevant experience<textarea required rows="4" /></label><label>Why do you want to join the team?<textarea required rows="5" /></label><label className="upload-field">Attach CV / résumé<input required type="file" accept=".pdf,.doc,.docx" /></label><button className="primary-action" type="submit">SUBMIT APPLICATION</button>{applicationSent && <p className="inline-success">Application details saved. Email delivery will activate when the hiring inbox is connected.</p>}</form></section><SiteFooter onNavigate={onNavigate} /></main>;
}
