import { MessageSquareText } from 'lucide-react';
import { addAdminRecord, updateAdminCollection } from '../api/adminStore';

export default function RequestsPage({ activeTab, filteredRequests, setSelectedItem }) {
  return <>
    <header className="admin-page-heading"><div><small>Enquiries · {activeTab}</small><h2>Custom requests</h2><p>Review the brief, prepare a quote and move approved work into fulfilment.</p></div></header>
    <div className="request-workbench">
      {filteredRequests.map(request => <article key={request.id}>
        <button className="request-summary" onClick={() => setSelectedItem({ type: 'request', title: request.name || 'Custom request', status: request.status, detail: request.note || request.service || 'No brief supplied.', request })}>
          <span className="customer-avatar"><MessageSquareText size={19} /></span><span><strong>{request.name || 'Unnamed customer'}</strong><small>{request.phone || 'No phone'} · {request.preferredDate || 'Date to confirm'}</small></span><span><small>Request</small><b>{request.service || request.selections?.join(', ') || 'Bespoke gift'}</b></span><em>{request.status === 'approved' ? 'Approved' : request.status === 'quote_needed' ? 'Quote needed' : 'New'}</em><i>→</i>
        </button>
        <div className="request-actions"><label>Confirmed quote (GHS)<input type="number" min="1" step="0.01" defaultValue={request.quoteTotal || request.estimateHigh || ''} placeholder="Enter final amount" disabled={request.status === 'converted'} onBlur={event => updateAdminCollection('requests', items => items.map(item => item.id === request.id ? { ...item, quoteTotal: Number(event.target.value || 0) } : item))} /></label><button disabled={request.status === 'converted'} onClick={() => updateAdminCollection('requests', items => items.map(item => item.id === request.id ? { ...item, status: 'quote_needed' } : item))}>Needs quote</button><button disabled={request.status === 'converted' || !Number(request.quoteTotal || request.estimateHigh)} onClick={() => updateAdminCollection('requests', items => items.map(item => item.id === request.id ? { ...item, status: 'approved', approvedAt: new Date().toISOString() } : item))}>Approve</button>{request.status === 'approved' && <button disabled={!Number(request.quoteTotal || request.estimateHigh)} onClick={() => { const seed = Date.now().toString().slice(-6); const total = Number(request.quoteTotal || request.estimateHigh); const qty = Number(request.quantity || 1); addAdminRecord('orders', { tracking: `GF-${seed}`, code: `REQ-${seed}`, customer: request.name, phone: request.phone, recipient: request.name, delivery: 'To confirm', customerNote: request.note, requestedDeliveryDate: request.preferredDate, paymentMethod: 'To confirm', paymentStatus: 'pending', items: [{ name: request.service || request.selections?.join(', ') || 'Custom gift request', qty, price: qty ? total / qty : total }], total, status: 'pending_payment' }); updateAdminCollection('requests', items => items.map(item => item.id === request.id ? { ...item, status: 'converted', convertedAt: new Date().toISOString() } : item)); }}>Create order</button>}<button className="is-danger" onClick={() => updateAdminCollection('requests', items => items.filter(item => item.id !== request.id))}>Delete</button></div>
      </article>)}
      {!filteredRequests.length && <div className="admin-empty-state"><MessageSquareText size={22} /><strong>No requests in {activeTab.toLowerCase()}</strong><p>New storefront enquiries will appear here automatically.</p></div>}
    </div>
  </>;
}
