import { useState } from 'react';
import { Check, Heart, X } from 'lucide-react';
import QuantityControl from '../components/QuantityControl';

export default function ProductDetail({ product, saved, onClose, onAdd, onToggleWishlist, onCustomize }) {
  const [quantity, setQuantity] = useState(1);
  const available = product.stock == null ? Infinity : Math.max(0, Number(product.stock));
  return <div className="flow-backdrop product-detail-backdrop" onClick={onClose}><section className="product-detail" role="dialog" aria-modal="true" aria-label={`${product.name} details`} onClick={event => event.stopPropagation()}><button className="round-icon close-flow" onClick={onClose} aria-label="Close product details"><X size={18} /></button><div className="product-detail-visual">{product.discountPercent > 0 && <span className="product-sale-badge">{product.discountPercent}% OFF</span>}<img src={product.image} alt={product.name} /></div><div className="product-detail-copy"><span>{product.tag}</span><h2>{product.name}</h2><p>{product.detail}</p><div className="product-detail-price">{product.discountPercent > 0 && <del>{product.originalPriceLabel}</del>}<strong>{product.priceLabel}</strong></div><div className="product-includes"><small>DETAILS &amp; BENEFITS</small>{product.includes.map(item => <p key={item}><Check size={14} />{item}</p>)}</div><div className="detail-order-row"><QuantityControl value={quantity} label={product.name} onDecrease={() => setQuantity(current => Math.max(1, current - 1))} onIncrease={() => setQuantity(current => available === Infinity ? current + 1 : Math.min(Math.max(available, 1), current + 1))} /><button className="primary-action" disabled={!available} onClick={() => { onAdd(product, quantity); onClose(); }}>{available ? `ADD ${quantity} TO ORDER` : 'OUT OF STOCK'}</button></div><div className="detail-secondary"><button onClick={() => onToggleWishlist(product.id)}><Heart size={16} fill={saved ? 'currentColor' : 'none'} />{saved ? 'SAVED' : 'SAVE GIFT'}</button><button onClick={() => { onClose(); window.setTimeout(() => onCustomize(product.name), 120); }}>CUSTOMIZE THIS GIFT</button></div><small className="merch-note">Final availability and delivery are confirmed before payment.</small></div></section></div>;
}
